touch ../D14TaxAdjustDetail.jsp
touch /sorc001/ehr/ehr.ear/ehrWeb.war/web/upload/D11TaxAdjust/upload.jsp
touch D11TaxAdjustGuide.jsp
touch D11TaxAdjustGuideTop.jsp
touch D11TaxAdjustBuild.jsp                    
touch D11TaxAdjustBuild01.jsp                  
touch D11TaxAdjustButton.jsp                   
touch D11TaxAdjustChange.jsp                   
touch D11TaxAdjustDetail.jsp                   
touch D11TaxAdjustEducationBuild.jsp                 
touch D11TaxAdjustEducationDetail.jsp                 
touch D11TaxAdjustFamily.jsp                   
touch D11TaxAdjustGibuBuild.jsp                
touch D11TaxAdjustGibuChange.jsp               
touch D11TaxAdjustGibuDetail.jsp               
touch D11TaxAdjustGibuPrint.jsp                
touch D11TaxAdjustGuide.jsp                    
touch D11TaxAdjustGuideBottom.jsp              
touch D11TaxAdjustGuideTop.jsp                 
touch D11TaxAdjustInfo.html                    
touch D11TaxAdjustInfo_B.html                  
touch D11TaxAdjustInfo_D.html                  
touch D11TaxAdjustInfo_H.html                  
touch D11TaxAdjustMedicalBuild.jsp             
touch D11TaxAdjustMedicalChange.jsp            
touch D11TaxAdjustMedicalDetail.jsp            
touch D11TaxAdjustMedicalPrint.jsp             
touch D11TaxAdjustPerson.jsp                   
touch D11TaxAdjustPreWorkBuild.jsp             
touch D11TaxAdjustPreWorkChange.jsp            
touch D11TaxAdjustPreWorkDetail.jsp            
touch D11TaxAdjustPreWorkSearch.jsp            
touch D11TaxAdjustSpecialBuild.jsp             
touch D11TaxAdjustSpecialChange.jsp            
touch D11TaxAdjustSpecialDetail.jsp            
touch D11TaxAdjustTaxBuild.jsp                 
touch D11TaxAdjustTaxChange.jsp                
touch D11TaxAdjustTaxDetail.jsp                
touch D11TaxAdjustCardBuild.jsp                 
touch D11TaxAdjustCardChange.jsp                
touch D11TaxAdjustCardDetail.jsp                 
touch D11TaxAdjustRentBuild.jsp                 
touch D11TaxAdjustRentChange.jsp                
touch D11TaxAdjustRentDetail.jsp                  
touch D11TaxAdjustPensionBuild.jsp                 
touch D11TaxAdjustPensionChange.jsp                
touch D11TaxAdjustPensionDetail.jsp                
